### ISSUE TITLE
Lacking support for split files

### ISSUE THREAD

**Issue by johann-lau** [discord-py-ui/discord-ui#113]
## Motivation

The official discord.py library supports loading extension commands from other files, so I think it is a good idea for discord_ui to have it as well. Otherwise, large bots can easily get to tens of thousands of lines in a single file.

## Reference code

To put this conveniently, here is the `bot.load_extension()` method definition:
```py
# In the Bot class
def load_extension(
        self,
        name: str,
        *,
        package: Optional[str] = None,
        extras: Optional[Dict[str, Any]] = None
    ) -> None:
            name = self._resolve_name(name, package)
            if name in self.__extensions:
                raise errors.ExtensionAlreadyLoaded(name)
        
            spec = importlib.util.find_spec(name)
            if spec is None:
                raise errors.ExtensionNotFound(name)
        
            self._load_from_module_spec(spec, name, extras=extras)
```

**Comment by 404kuso** [comment]
I don't know if I'm missunderstanding something, but why can't you just use discord.py's `load_extension`? 
Both [`.add_cog`](https://github.com/discord-py-ui/discord-ui/blob/main/discord_ui/client.py#L135) and [`.remove_cog`](https://github.com/discord-py-ui/discord-ui/blob/main/discord_ui/client.py#L152) get overwritten by default in order to get application commands on cogs working.

If you want to split files, just use the `cog` module of discord_ui together with discord.py's cog system

**other_file.py**
```py
from discord_ui import cogs
from discord.ext import commands
class MyCog(commands.Cog):
    @cogs.slash_command(...)
    async def my_command(self, ctx):
        ...
def setup(bot):
    bot.add_cog(MyCog())
```

**main.py**
```py
...

bot.load_extension('other_file')
```

**Comment by johann-lau** [comment]
How about individual commands? I often use `@ui_.slash.command()`, and I am wondering if there is a similar way of doing this. Thanks!

**Comment by johann-lau** [comment]
OK, I've found a way to do this. In case someone is looking here, I'll post the solution for non-cogs:
**bot.py**
```py
ui_ = ui.UI(bot)
bot_.load_extension("other")
```
**other.py**
```py
# context commands if any (as usual)

@bu.slash.command(name="tester", description="Some tester.")
async def tester(ctx):
    ...

def setup:
    ...
    # Do not add any line referring to the tester command
```
