### ISSUE TITLE
Add support for discord.Client() clients.

### ISSUE THREAD

**Issue by f1oppa** [discord-py-ui/discord-ui#115]
I want to use this extension with my discord.Client() client, but i get this error:
![image](https://user-images.githubusercontent.com/69513672/151201917-9657f523-620b-415f-b89a-7e7d33397faa.png)

**Comment by 404kuso** [comment]
I cant really add support for `discord.Client` because you can only register one listener to one event. The libary uses two event listeners for `on_socket_response`, so that wouldn't really work since that would mean one of the listeners would get overwritten by the other one. And even if I manage to clean everything up and use one event listener, there's still a chance that the event listener of the lib would get overwritten by the user.

**Comment by f1oppa** [comment]
Okay, i understand. I also managed to solve my problem with commands.bot(). One more thing, if someone uses discord.Client() can you print a warning that says for example "use commands.bot()"?

**Comment by kvsxxx** [comment]
yeah ill add that
