### ISSUE TITLE
Ninja mode gives 404 Not Found

### ISSUE THREAD

**Issue by Mabi19** [discord-py-ui/discord-ui#90]
Responding to a select menu interaction using ninja mode gives a 404 Not Found, with error code 10062 (Unknown interaction). I tested with sending a message, and it works. (I'm receiving the event through a `@commands.Cog.listener("on_menu_select")` decorated function, since I couldn't find a way to use the other ways with cogs; actually, better support for cogs would be great). Sorry for not providing an example, I'm in a hurry right now.

**Comment by 404kuso** [comment]
thank you for your report again, and I'm sorry for all of our issues. 

The problem was, that if you used ninja_mode, it would respond quitely to the component but because I forgot to return after the response, it would try to respond to the interaction again with a normal method. Thank you very much


(I'll try add cog support)
